"""Bundle backend configuration translations into OASX for offline startup.

Run from the repository root after updating assets/i18n/zh-CN.json.
The settings catalog is derived from public schemas, never user configurations.
"""

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/i18n/zh-CN.json"
BUNDLE = ROOT / "oasx/lib/translation/cn_parts/cn_backend_config.dart"
CATALOG = ROOT / "oasx/test/fixtures/settings_translation_keys.json"


def render_bundle(translations):
    def dart_string(value):
        return json.dumps(value, ensure_ascii=False).replace("$", r"\$")

    entries = "\n".join(
        f"  {dart_string(key)}: {dart_string(value)},"
        for key, value in translations.items()
    )
    return (
        "// GENERATED by dev_tools/sync_oasx_translations.py; edit assets/i18n/zh-CN.json.\n"
        "// ignore_for_file: non_constant_identifier_names\n"
        "part of i18n;\n\n"
        "final Map<String, String> _cn_backend_config = {\n"
        + entries
        + "\n};\n"
    )


def settings_catalog():
    from module.config.config_menu import ConfigMenu
    from module.config.config_model import ConfigModel

    # model_construct avoids loading or persisting any real profile.
    model = ConfigModel.model_construct()
    keys = {}
    tasks = [task for group in ConfigMenu().gui_menu_list.values() for task in group]

    def add(kind, value, context):
        if not value or not re.search(r"[A-Za-z]", str(value)):
            return
        # Already-Chinese labels and prose are displayed directly.
        if re.search(r"[\u3400-\u9fff]", str(value)):
            return
        keys.setdefault((kind, str(value)), set()).add(context)

    for task in tasks:
        for group, arguments in model.script_task(task).items():
            add("group", group, task)
            for arg in arguments:
                context = f"{task}/{group}/{arg['name']}"
                add("label", arg["name"], context)
                add("help", arg.get("description", ""), context)
                for choice in arg.get("enumEnum", []):
                    add("enum", choice, context)
    return {
        "tasks": tasks,
        "keys": [
            {"kind": kind, "key": key, "contexts": sorted(contexts)}
            for (kind, key), contexts in sorted(keys.items())
        ],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale")
    args = parser.parse_args()
    expected = {
        BUNDLE: render_bundle(json.loads(SOURCE.read_text(encoding="utf-8"))),
        CATALOG: json.dumps(settings_catalog(), ensure_ascii=False, indent=2) + "\n",
    }
    for path, content in expected.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Out of date: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("OASX configuration translations and public schema catalog are current.")


if __name__ == "__main__":
    main()
